TMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('allauth.urls')),
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
    path('users/', include("users.urls")),
    path('goals/', include("goals.urls")),
    path('rewards/', include("rewards.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

goals/urls.py
from django.urls import path
from .views import create_goal, goal_list, goal_detail

app_name = "goals"

urlpatterns = [
    path("create/", create_goal, name="create_goal"),
    path("", goal_list, name="goal_list"),
    path("<int:pk>/", goal_detail, name="goal_detail"),
]

main/urls.py
from django.urls import path
from main import views;


app_name = "main"

urlpatterns = [
    path('', views.home, name="landing_page"),
    path('dashboard', views.dashboard,name="dashboard"),
    path('emp/profile/<int:pk>', views.emp_profile, name="emp_profile"),
    path('emp/profile/edit/<int:pk>', views.edit_profile, name="profile_edit"),
    path('emp/details/<int:pk>', views.emp_details, name="emp_details"),   
    path('emp/list', views.emp_list, name="emp_list"),
    path('emp/edit/<int:pk>', views.emp_edit, name="emp_edit"),
    path('emp/skillgap/<int:pk>', views.emp_skillgap, name="emp_skillgap"),
    
    path('feedback', views.feedback, name="feedback"),

    path('emp/analytics', views.analytics, name="analytics"),
    path('posts', views.post_view, name="posts"),
    path('emp/succession', views.succession, name="succession"),
    path('emp/promotion', views.promotion, name="promotion"),
    path('emp/reports', views.reports, name="reports"),
    path('add-training/', views.add_training_program, name='add_training_program'),

    path('trainings/', views.training_programs_view, name='emp_training'),
    path('trainings/enroll/<int:program_id>/', views.enroll_training, name='enroll_training'),

    path('jobs', views.job_list, name='job_list'),  # View all jobs
    path('jobs/post/', views.post_job, name='post_job'),  # Post a job
    path('jobs/<int:pk>/', views.job_detail, name='job_detail'),  # View a job
    path('jobs/<int:pk>/edit/', views.edit_job, name='edit_job'),  # Edit a job
    path('jobs/<int:pk>/apply/', views.apply_job , name='apply_job'),
    path("my-applied-jobs/", views.applied_jobs, name="applied_jobs"),
    path("update_application_status/", views.update_application_status, name="update_application_status"),

    path('talent/', views.talent_view, name='talent'),
    path('commonfeedback/', views.commonfeedback_view, name='commonfeedback_view'),

    path('program/<int:program_id>/', views.program_detail, name='program_detail'),
    path('program/<int:program_id>/enroll/', views.enroll_in_program, name='enroll_in_program'),

    path('profile/edit/', views.common_edit_profile, name='common_edit_profile'),





]

rewards/urls.py
from django.urls import path
from .views import reward_list,reward_detail, edit_reward, create_reward

app_name = "rewards"

urlpatterns = [
    path('', reward_list, name='reward_list'),
    path('<int:program_id>/', reward_detail, name='reward_detail'),
    path('create/', create_reward, name='create_reward'),
    path('<int:program_id>/edit/', edit_reward, name='edit_reward'),



]

templates/base.html
{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Talent HR System</title>
  <script src="https://unpkg.com/@tailwindcss/browser@4"></script>
  <script src="https://cdn.tailwindcss.com"></script>
  
</head>
<body class="bg-gray-100">

  <!-- Navbar -->
  <nav class="bg-white shadow-md">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex justify-center items-center h-16 gap-8">
        <!-- Logo -->
        <div class="flex-shrink-0">
          <a href="/" class="text-2xl font-bold text-blue-600">TalentHub</a>
        </div>
        <!-- Links -->
        <div class="hidden md:flex space-x-6">
          {% if user.is_authenticated %}
          
          {% if user.last_name == "manager" or user.last_name == "HR" %}
          <a href="{% url 'main:dashboard' %}" class="text-gray-700 hover:text-blue-600 font-medium">Dashboard</a>
          {% endif %}

          <a href="{% url 'main:emp_profile' pk=user.id %}" class="text-gray-700 hover:text-blue-600 font-medium">Profile</a>
          <a href="{% url 'main:job_list' %}" class="text-gray-700 hover:text-blue-600 font-medium">Jobs</a>
          <a href="{% url 'goals:goal_list' %}" class="text-gray-700 hover:text-blue-600 font-medium">Goals</a>
          
          {% if user.last_name == "manager" or user.last_name == "HR" %}
          <a href="{% url 'main:emp_list' %}" class="text-gray-700 hover:text-blue-600 font-medium">EmployeeAnalysis</a>
          {% endif %}

          

          
          {% if user.last_name == "employee" %}
          
          
          <a href="{% url 'main:applied_jobs' %}" class="text-gray-700 hover:text-blue-600 font-medium">Applied Jobs</a>
          
          <a href="{% url 'main:emp_skillgap' pk=user.id %}" class="text-gray-700 hover:text-blue-600 font-medium">Skillgap</a>
          
          {% endif %}
          <a href="{% url 'rewards:reward_list' %}" class="text-gray-700 hover:text-blue-600 font-medium">Rewards</a>
          <a href="{% url 'main:commonfeedback_view' %}" class="text-gray-700 hover:text-blue-600 font-medium">Feedback</a>
          <a href="{% url 'main:emp_training'%}" class="text-gray-700 hover:text-blue-600 font-medium">Trainings</a>
       
          
          <a href="{% url 'main:feedback' %}" class="text-gray-700 hover:text-blue-600 font-medium">Performance Review</a>

          {% if user.last_name == "manager" or user.last_name == "HR" %} 
          <a href="{% url 'main:analytics' %}" class="text-gray-700 hover:text-blue-600 font-medium">Analytics</a>
          <a href="{% url 'main:talent' %}" class="text-gray-700 hover:text-blue-600 font-medium">Talent Pool</a>
          {% endif %}

         


          {% endif %}
          
        
        </div>
        <!-- Profile Section -->
        <div class="ml-4 relative flex flex-row">
          <button class="flex items-center text-gray-600 hover:text-blue-600 focus:outline-none">
          <a href="{% url 'main:emp_profile' pk=user.id %}">
            <span class="ml-2 hidden md:block font-medium">{{user.username}}</span>
          </a>
          </button>
          <button class="flex items-center text-gray-600 hover:text-blue-600 focus:outline-none">
            <a href="/accounts/logout">
              <span class="ml-2 hidden md:block font-medium">Logout</span>
            </a>
            </button>
        </div>
        <!-- Hamburger Menu -->
        <div class="flex md:hidden">
          <button id="mobile-menu-btn" class="text-gray-600 hover:text-blue-600 focus:outline-none">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              class="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M4 6h16M4 12h16m-7 6h7"
              />
            </svg>
          </button>
        </div>
      </div>
    </div>
    <!-- Mobile Menu -->
    <div id="mobile-menu" class="hidden md:hidden">
      <div class="px-2 pt-2 pb-3 space-y-1">
        {% if user.is_authenticated %}
          
          {% if user.last_name == "manager" or user.last_name == "HR" %}
          <a href="{% url 'main:dashboard' %}" class="text-gray-700 hover:text-blue-600 font-medium">Dashboard</a>
          {% endif %}

          <a href="{% url 'main:emp_profile' pk=user.id %}" class="text-gray-700 hover:text-blue-600 font-medium">Profile</a>
          
          {% if user.last_name == "manager" %}
          <a href="{% url 'main:emp_list' %}" class="text-gray-700 hover:text-blue-600 font-medium">EmployeeList</a>
          {% endif %}

          
          {% if user.last_name == "employee" %}
          <a href="{% url 'main:emp_skillgap' pk=user.id %}" class="text-gray-700 hover:text-blue-600 font-medium">Skillgap</a>
          <a href="{% url 'main:job_list' %}" class="text-gray-700 hover:text-blue-600 font-medium">Jobs</a>
          <a href="{% url 'main:applied_jobs' %}" class="text-gray-700 hover:text-blue-600 font-medium">Applied Jobs</a>
          
          {% endif %}

          


          <a href="{% url 'main:emp_training' %}" class="text-gray-700 hover:text-blue-600 font-medium">Trainings</a>
          
          <a href="{% url 'main:feedback' %}" class="text-gray-700 hover:text-blue-600 font-medium">Feedback</a>

          {% if user.last_name == "manager" or user.last_name == "HR" %}
          <a href="{% url 'main:analytics' %}" class="text-gray-700 hover:text-blue-600 font-medium">Analytics</a>
          {% endif %}

          <a href="{% url 'main:posts' %}" class="text-gray-700 hover:text-blue-600 font-medium">Posts</a>

          {% if user.last_name == "manager" %}
          <a href="{% url 'main:succession' %}" class="text-gray-700 hover:text-blue-600 font-medium">Succession</a>
          {% endif %}

          {% if user.last_name == "manager" %}
          <a href="{% url 'main:promotion' %}" class="text-gray-700 hover:text-blue-600 font-medium">Promotion</a>
          {% endif %}

          {% if user.last_name == "HR" %}
          <a href="{% url 'main:reports' %}" class="text-gray-700 hover:text-blue-600 font-medium">Reports</a>
          {% endif %}


          {% endif %}


      </div>
    </div>
  </nav>

  {% block content %}
  {% endblock %}




  <!-- Footer -->
  <footer class="bg-gray-800 text-white py-8">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <p class="text-center">&copy; 2025 TalentHub. All rights reserved.</p>
    </div>
  </footer>

</body>
</html>